version: '3'

services:
  influxdb:
    restart: always
    image: influxdb:1.8
    ports:
      - "8087:8086"
    volumes:
      - "./data/influxdb/:/var/lib/influxdb"
    environment:
      INFLUXDB_ADMIN_USER: admin
      INFLUXDB_ADMIN_PASSWORD: password
      INFLUXDB_DB: speedtest

  grafana:
    restart: always
    image: grafana/grafana:5.4.4
    volumes:
      - "./docker/grafana/provisioning:/etc/grafana/provisioning"
    environment:
      VIRTUAL_HOST: ${DOMAIN}
      VIRTUAL_PORT: 3000
      GF_SERVER_ROOT_URL: ${DOMAIN}
      GF_SECURITY_ADMIN_PASSWORD: admin
      GF_AUTH_ANONYMOUS_ENABLED: ${GF_AUTH_ANONYMOUS_ENABLED}
    depends_on:
      - influxdb

  speedtest:
    restart: always
    image: frdmn/speedtest-grafana:latest
    container_name: speedtest
    environment:
      SPEEDTEST_INTERVAL: ${SPEEDTEST_SPEEDTEST_INTERVAL}
      SPEEDTEST_HOST: ${SPEEDTEST_HOST}
    depends_on:
      - influxdb
networks:
  default:
    external:
      name: nginx-proxy
