version: '3'
services:
  speedtest:
    container_name: speedtest
    build: docker-speedtest-analyser-master/
    restart: unless-stopped
    volumes:
      -  ${MEDIA_DIR}/speed-test:/var/www/html/data
    environment:
      VIRTUAL_HOST: ${DOMAIN}
      CRONJOB_ITERATION: ${SPEEDTEST_SPEEDTEST_INTERVAL}
      SPEEDTEST_PARAMS: '--secure'
networks:
  default:
    external:
      name: nginx-proxy

