version: "3"

services:
  nginx-proxy:
    image: traskit/nginx-proxy:latest
    ports:
      - '80:80'
    environment:
      DEFAULT_HOST: ${PIHOLE_DOMAIN}
    volumes:
      - '/var/run/docker.sock:/tmp/docker.sock'
    restart: always
    networks:
      - nginx-proxy
networks:
  nginx-proxy:
    external:
      name: nginx-proxy