version: "3.3"

services:
  peertube:
    # If you don't want to use the official image and build one from sources
    # build:
    #   context: .
    #   dockerfile: ./support/docker/production/Dockerfile.buster
    image: chocobozzz/peertube:production-buster
    env_file:
      - .env
    # Traefik labels are suggested as an example for people using Traefik,
    # remove them if you are using another reverse proxy.
    # labels:
    #   traefik.enable: "true"
    #   traefik.frontend.rule: "Host:${PEERTUBE_WEBSERVER_HOSTNAME}"
    #   traefik.port: "9000"
    # # If you don't want to use a reverse proxy (not suitable for production!)
    ports:
      - "8081:9000"
    volumes:
      - ./media/hdvideos:/data
      - ./peertube/config:/config
    depends_on:
      - postgres
      - redis
      - postfix
    restart: "always"

  postgres:
    image: arm32v7/postgres:10-alpine
    env_file:
      - .env
    volumes:
      - ./peertube/db:/var/lib/postgresql/data
    restart: "always"
    # labels:
    #   traefik.enable: "false"

  redis:
    image: redis:4-alpine
    volumes:
      - ./peertube/redis:/data
    restart: "always"
    labels:
      traefik.enable: "false"

  postfix:
    image: mwader/postfix-relay
    env_file:
      - .env
    # labels:
    #   traefik.enable: "false"
    restart: "always"

# networks:
#   default:
#     ipam:
#       driver: default
#       config:
#       - subnet:  172.18.0.0/16