version: "3"

services:
  youtubedl:
     build: .
     restart: always
     volumes:
        - ./appdata:/app/appdata
        - /mnt/usb/jellyfin/media/youtubedl-audio:/app/audio
        - /mnt/usb/jellyfin/media/youtubedl-video:/app/video
        - ./subscriptions:/app/subscriptions
        - ./users:/app/users
     environment:
        VIRTUAL_HOST: dl.thisnode.info
        VIRTUAL_PORT: 17442
networks:
  default:
    external:
      name: nginx-proxy
