version: "3"
services:
  feedless:
    build: rede-social-comunitaria-master
    restart: always
    network_mode: host
    env_file: .env
    volumes:
      - feedless_ssb:/root/.ssb

networks:
  default:
    external:
      name: nginx-proxy
volumes:
  feedless_ssb:

