version: "3"
services:
  feedless:
    build: ./app/web
    restart: always
    network_mode: host
    ports:
      - "3000:3000"
    env_file: .env
    volumes:
      - feedless_ssb:/root/.ssb
volumes:
  feedless_ssb:

