version: "3"

services: 
    cadvisor:
        image: zcube/cadvisor
        container_name: cadvisor
        volumes:
           - /:/rootfs:ro
           - /var/run:/var/run:rw
           - /sys:/sys:ro
           - /var/lib/docker/:/var/lib/docker:ro
           - /cgroup:/cgroup:ro
        environment:
            VIRTUAL_HOST: cadvisor.thisnode.info
            VIRTUAL_PORT: 8080
        privileged: true
        restart: always
networks:
  default:
    external:
      name: nginx-proxy

