version: "3"
services:
  jellyfin:
    image: jellyfin/jellyfin
    restart: unless-stopped 
    volumes:
        - ${MEDIA_DIR}/jellyfin/config:/config
        - ${MEDIA_DIR}/jellyfin/cache:/cache
        - ${MEDIA_DIR}/jellyfin/media:/media
        - /opt/vc/lib:/opt/vc/lib
    environment:
        PUID: 1000
        PGID: 1000
        VIRTUAL_HOST: ${JELLYFIN_DOMAIN}
        VIRTUAL_PORT: 8096
    devices:
      - /dev/vchiq:/dev/vchiq #hardware acceleration for Rasp
      - /dev/vcsm:/dev/vcsm #hardware acceleration for Rasp
networks:
  default:
    external:
      name: nginx-proxy
