version: "3"
services:
  jellyfin:
    image: jellyfin/jellyfin
    restart: unless-stopped
    ports:
        - "8096:8096"
    volumes:
        -  ${MEDIA_DIR}/jellyfin/config:/config
        -  ${MEDIA_DIR}/jellyfin/cache:/cache
        -  ${MEDIA_DIR}/jellyfin/media:/media
        - /opt/vc/lib:/opt/vc/lib
    environment:
        PUID: 1000
        PGID: 1000

