version: '3'

services:
  tube:
    container_name: tube
    image: prologic/tube:latest
    restart: unless-stopped
    volumes:
      - ${MEDIA_DIR}/tube:/data # Tube data
    environment:
      VIRTUAL_HOST: ${TUBE_DOMAIN}
    networks:
      - proxy
volumes:
  db_data:
networks:
  proxy: