version: '3'

services:
  tube:
    container_name: tube
    image: prologic/tube
    restart: unless-stopped
    volumes:
      - ./data:/data # Tube data
    environment:
      VIRTUAL_HOST: ${DOMAINS}
      LETSENCRYPT_HOST: ${DOMAINS}
      LETSENCRYPT_EMAIL: ${LETSENCRYPT_EMAIL}
networks:
  default:
    external:
      name: ${NETWORK}
volumes:
  db_data:
