version: "3"

services:
  kolibri:
     build: .
     restart: always
     volumes:
        - ${MEDIA_DIR}/kolibri:/root/.kolibri
     ports:
        - "8080:8080"
     environment:
        VIRTUAL_HOST: ${KOLIBRI_DOMAIN}
        VIRTUAL_PORT: 8080
networks:
  default:
    external:
      name: nginx-proxy
