version: "3"

# https://github.com/pi-hole/docker-pi-hole/blob/master/README.md

services:
  pihole:
    image: pihole/pihole:latest
    privileged: true
    networks:
      - nginx-proxy
    dns:
      - 127.0.0.1
      - 1.1.1.1
    ports:
      - '53:53/tcp'
      - '53:53/udp'
      - "67:67/udp"
      - '8053:80/tcp'
      - "443:443/tcp"
    volumes:
      - './etc-pihole/:/etc/pihole/'
      - './etc-dnsmasq.d/:/etc/dnsmasq.d/'
      # run `touch ./var-log/pihole.log` first unless you like errors
      # - './var-log/pihole.log:/var/log/pihole.log'
    # Recommended but not required (DHCP needs NET_ADMIN)
    #   https://github.com/pi-hole/docker-pi-hole#note-on-capabilities
    cap_add:
      - NET_ADMIN
    environment:
      ServerIP: ${SERVER_IP}
      PROXY_LOCATION: pihole
      VIRTUAL_HOST: ${PIHOLE_DOMAIN}
      VIRTUAL_PORT: 80
    extra_hosts:
      # Resolve to nothing domains (terminate connection)
      - 'nw2master.bioware.com nwn2.master.gamespy.com:0.0.0.0'
      # LAN hostnames for other docker containers using jwilder
      - 'moinho.com:${SERVER_IP}'
      - 'filtro ${PIHOLE_DOMAIN}:${SERVER_IP}'
      - 'admin ${PORTAINER_DOMAIN}:${SERVER_IP}'
      - 'rede ${GRAFANA_DOMAIN}:${SERVER_IP}'
      # - 'ghost ghost.moinho.lan:${SERVER_IP}'
      # - 'wordpress wordpress.moinho.lan:${SERVER_IP}'
    restart: always
networks:
  nginx-proxy:
    external:
      name: nginx-proxy